Karya_yojana/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView
# from .views import SecuredLoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('karya.urls')),

    path('login/', LoginView.as_view(template_name = 'karya/login.html'), name='login_url'),
    path('logout/', LogoutView.as_view(), name='logout_url'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
]

karya/urls.py
from django.urls import path
from .views import IndexView, CreateAccountView
from django.views.generic.base import TemplateView


app_name = 'karya'

urlpatterns = [
    path('', IndexView.as_view(), name='index_page'),
    path('register/', CreateAccountView.as_view(template_name = 'karya/register.html'), name='register_url')
]

karya/models.py
from django.db import models
from django.contrib.auth.models import User


class Employee(models.Model):
    employee_id = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)
    profile_img = models.ImageField(default = 'default.png', upload_to = 'profile_pics', blank = True, null = True)
    def __str__(self):
        return self.employee_id


class Team(models.Model):
    team_name   = models.CharField(max_length=255, primary_key=True)
    member      = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.team_name


class Project(models.Model):
    name    = models.CharField(max_length=255)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_by_user')
    assigned_team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='assigned_to_team')
    create_time= models.DateTimeField()
    team_id = models.ForeignKey(Team, on_delete=models.CASCADE)

TASK_STATUS_CHOICE = (
        ('not started','Not Started'),
        ('in progress', 'In Progress'),
        ('on hold', 'On Hold'),
        ('completed', 'Completed'),
        ('user accepted', 'User Accepted'),
)

class Task(models.Model):
    task_title      = models.CharField(max_length=255)
    created_by      = models.OneToOneField(User, on_delete=models.CASCADE, related_name='created_by')
    assigned_to     = models.OneToOneField(User, on_delete=models.CASCADE, related_name='assigned_to_user')
    create_time     = models.DateTimeField()
    user_story      = models.TextField()
    status          = models.CharField(max_length=50, choices=TASK_STATUS_CHOICE, default='select')

    def __str__(self):
        return self.task_title


# class AboutTask(models.Model):
#     task_id = models.ForeignKey(Task, on_delete=models.CASCADE)
#     comments = models.TextField()

karya/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegistrationForm(UserCreationForm):
    username = forms.CharField(max_length=32, widget=forms.TextInput(attrs={'class': 'form-control form-control-user', 'id': 'exampleUsername', 'placeholder': 'Username'}))
    first_name = forms.CharField(max_length=32, widget=forms.TextInput(attrs={'class': 'form-control form-control-user', 'id': 'exampleFirstName', 'placeholder': 'First Name'}))
    last_name = forms.CharField(max_length=32, widget=forms.TextInput(attrs={'class': 'form-control form-control-user', 'id': 'exampleLastName', 'placeholder': 'Last Name'}))
    email = forms.EmailField(max_length=255, widget=forms.TextInput(attrs={'class': 'form-control form-control-user', 'id': 'exampleInputEmail', 'placeholder': 'Email Address'}))
    password1 = forms.CharField(strip=False, widget=forms.PasswordInput(attrs={'class': 'form-control form-control-user', 'id': 'exampleInputPassword', 'placeholder': 'Password'}))
    password2 = forms.CharField(strip=False, widget=forms.PasswordInput(attrs={'class': 'form-control form-control-user', 'id': 'exampleRepeatPassword', 'placeholder': 'Password Confirmation'}))

    password1.help_text = ''
    password2.help_text = ''

    class Meta:
        model = User
        fields = ("username", "first_name", "email", 'last_name')

Karya_yojana/views.py
from django.contrib.auth.views import LoginView
from django.shortcuts import render


# class SecuredLoginView(LoginView):
#     pass

karya/views.py
from django.shortcuts import render
from django.views import View
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic.base import TemplateView

from django.urls import reverse_lazy
from django.views import generic
from . forms import RegistrationForm

class IndexView(View):
    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        # return render(request, 'karya/index.html', {})
        return render(request, 'base.html', {})

    def post(self, request, *kwargs):
        pass

class CreateAccountView(generic.CreateView):
    form_class = RegistrationForm
    print(form_class)
    success_url = reverse_lazy('logout_url')
    template_name = 'karya/register.html'
    # def get(self, request, *args, **kwargs):
    #     return render(request, 'karya/register.html', {})

karya/templates/karya/forgot-password.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SB Admin 2 - Forgot Password</title>

  <!-- Custom fonts for this template-->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                    <p class="mb-4">We get it, stuff happens. Just enter your email address below and we'll send you a link to reset your password!</p>
                  </div>
                  <form class="user">
                    <div class="form-group">
                      <input type="email" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Email Address...">
                    </div>
                    <a href="login.html" class="btn btn-primary btn-user btn-block">
                      Reset Password
                    </a>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="register.html">Create an Account!</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="login.html">Already have an account? Login!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

karya/templates/karya/login.html
{% extends 'base.html'%}
{% load static %}

<head>
  {% block head %}
  {% endblock %}
</head>

<body class="bg-gradient-primary">
  {% block body %}
  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                  </div>
                  <form class="user" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" name="username" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Email Address...">
                    </div>
                    <div class="form-group">
                      <input type="password" class="form-control form-control-user" name="password" id="exampleInputPassword" placeholder="Password">
                    </div>
                    <div class="form-group">
                      <div class="custom-control custom-checkbox small">
                        <input type="checkbox" class="custom-control-input" id="customCheck">
                        <label class="custom-control-label" for="customCheck">Remember Me</label>
                      </div>
                    </div>
                    <button type="submit" name="button" class="btn btn-primary btn-user btn-block">
                      Login
                    </button>
                    <hr>
                    <a href="index.html" class="btn btn-google btn-user btn-block">
                      <i class="fab fa-google fa-fw"></i> Login with Google
                    </a>
                    <a href="index.html" class="btn btn-facebook btn-user btn-block">
                      <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook
                    </a>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="{% url 'password_reset' %}">Forgot Password?</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="{% url 'karya:register_url' %}">Create an Account!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="js/sb-admin-2.min.js"></script>
{% endblock %}
</body>

</html>

karya/templates/karya/register.html
{% extends 'base.html'%}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  {% block head %}
  {% endblock %}

</head>

<body class="bg-gradient-primary">
  {% block body %}
  <div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
              </div>
              <form class="user" method="POST">
                {% csrf_token %}
                <!-- {{form.as_p}} -->
                <div class="form-group">
                  {{form.username}}
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    {{form.first_name}}
                  </div>
                  <div class="col-sm-6">
                    {{form.last_name}}
                  </div>
                </div>
                <div class="form-group">
                  {{form.email}}
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    {{form.password1}}
                  </div>
                  <div class="col-sm-6">
                    {{form.password2}}
                  </div>
                </div>
                <button type="submit" name="button" class="btn btn-primary btn-user btn-block">Register Account</button>
                <hr>
                <a href="index.html" class="btn btn-google btn-user btn-block">
                  <i class="fab fa-google fa-fw"></i> Register with Google
                </a>
                <a href="index.html" class="btn btn-facebook btn-user btn-block">
                  <i class="fab fa-github"></i> Register with Github
                </a>
              </form>
              <hr>
              <div class="text-center">
                <a class="small" href="{% url 'password_reset' %}">Forgot Password?</a>
              </div>
              <div class="text-center">
                <a class="small" href="{% url 'login_url' %}">Already have an account? Login!</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="js/sb-admin-2.min.js"></script>
{% endblock %}
</body>

</html>